### ISSUE TITLE
Beefcake 1.0.1 breaking riemann-client

### ISSUE THREAD

**Issue by peterneubauer** [protobuf-ruby/beefcake#63]
See https://github.com/aphyr/riemann-tools/issues/103 for details. This seems to be a beefcake issue with the latest release.

**Comment by bkerley** [comment]
1.0.1 or 1.1.0.pre1 ? Or both?

**Comment by peterneubauer** [comment]
I think I saw the error in both.

**Comment by bkerley** [comment]
TO-DO:

- [ ] Figure out what a `Riemann::Event` is, and how it's being used
- [ ] Minimize test case to particular error
- [ ] Fix error

**Comment by bkerley** [comment]
This has been fixed in version 1.1.0. Thanks for your help narrowing down this issue!
