### ISSUE TITLE
question: why use '.pb.rb' extension for generated classes?

### ISSUE THREAD

**Issue by alexdean** [protobuf-ruby/beefcake#67]
i'm curious why beefcake [generates ruby classes with an extension `.pb.rb`](https://github.com/protobuf-ruby/beefcake/blob/32a7f7265d1b1b45c8ec1572c5b02841809df2b9/lib/beefcake/generator.rb#L150).

currently i rename the classes back to just `.rb` so they work with rails auto-loading. but curious why they're generated this way in the first place.

**Comment by bkerley** [comment]
If I had to guess, it's to make it more obvious that the files are machine-generated, but this code predates my time on the project (/cc @streadway ).

For what it's worth, my main beefcake-using project has a [rake task that concatenates the `.pb.rb` files into a single .rb file][1], and [doesn't autoload][2].

[1]: https://github.com/basho/riak-ruby-client/blob/eb18edbf44ead2b1d5cb3360bd3c0254ccf21249/Rakefile#L102-L104
[2]: https://github.com/basho/riak-ruby-client/blob/eb18edbf44ead2b1d5cb3360bd3c0254ccf21249/lib/riak/client/beefcake_protobuffs_backend.rb#L13

**Comment by alexdean** [comment]
thanks for the info. much appreciated.
