### ISSUE TITLE
.proto file generator

### ISSUE THREAD

**Issue by danielpclark** [protobuf-ruby/beefcake#68]
Feature Request

Currently you have proto to ruby.  I'd love it to have a generator the other way as well.  Write first in Ruby, then export to .proto files for other devs to use.

**Comment by danielpclark** [comment]
I'd be interested in helping if that's what you would need for this.

**Comment by bkerley** [comment]
I don't have a particular use for this, but it sounds like a fun project! I'd recommend putting it in its own gem, since versioning a ruby to protobuffs compiler would mostly be independent of this serialization library's version.

**Comment by danielpclark** [comment]
Good point!  I may get started on this shortly.

**Comment by bkerley** [comment]
Cool! If you want some of the internal beefcake APIs about fields on an object to be made public/reliable/static, we can probably do that.
